### ISSUE TITLE
Why did you choose AGPL license?

### ISSUE THREAD

**Issue by leopd** [isik-kaplan/django_http_exceptions#5]
This seems like a useful little package.  But no way I'm going to use it with the AGPL license.

**Comment by isik-kaplan** [comment]
I agree(I learnt that it basically asks you to have your project open source also, right?), this was one of my first projects and I still to date don't know how should I licence my packages. If you don't mind me asking, can you change the licence just like that? And if so, do you have licence suggestion that I should go with for projects small-sized like this one?

**Comment by qcoumes** [comment]
I myself use the [MIT License](https://en.wikipedia.org/wiki/MIT_License) for such project.

Technically, you need everybody who contributed on your project to agree to change the license. As far as I know, i'm the only other contributor, and you can do whatever you like.

**Comment by isik-kaplan** [comment]
Well, that actually sounds lovely, I'll change the licence to either MIT or something like that first chance I get and close this issue with the commit. Thanks for the input guys!

**Comment by leopd** [comment]
That would be great, thanks!  

Super quick summary from my experience (I'm not a lawyer) - AGPL is aggressively designed to force companies to share their code open source.  GPL was designed to do that too, but there's a giant loophole for server-side software; so AGPL closes that loop-hole.  MIT & BSD are super neutral licenses - do what you want, don't bother the authors.  Most businesses are perfectly happy to use MIT & BSD code.  Apache is the most business friendly, explicitly granting patent rights and such.
